CREATE TABLE artists (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    artist TEXT NOT NULL,
    genre TEXT
);

CREATE TABLE dogs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER CHECK (age > 0),
    owner_name TEXT
)

CREATE TABLE cities (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    city TEXT NOT NULL,
    state TEXT NOT NULL
)

CREATE TABLE foods (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dish TEXT NOT NULL,
    country_of_origin TEXT NOT NULL,
    spice_level BOOLEAN NOT NULL
)